version: '3.7'

services:
   web:
    build: ./src/
    command: python app/server/app.py run 0.0.0.0
    volumes:
      - ./src:/usr/src/app/server
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
   db:
    image: kartoza/postgis:13.0
    container_name: postgres_db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=animaldb
volumes:
  postgres_data:
