version: '3.8'

services:
   web:
    build: ./
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - ./app/server:/usr/src/app/server
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
   db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
    env_file:
      - ./.env.prod.db
volumes:
  postgres_data:
